# Conic Launcher
# Copyright 2022-2024 Broken-Deer and contributors. All rights reserved.
# SPDX-License-Identifier: GPL-3.0-only

name: 🐞 Bug Report
title: "[Bug] "
description: Report a bug
labels: ["type: bug", "status: needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/conic-apps/launcher/issues?q=is%3Aissue) about this problem first.
        2. Make sure it's an issue with Conic Launcher and not something else you are using.
        3. Remember to follow our community guidelines and be friendly.

  - type: markdown
    attributes:
      value: |
        ## Basic Infomations

  - type: input
    id: version
    attributes:
      label: Launcher Version
      description: Please enter the version of the launcher you are using.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Please select the OS you are using.
      options:
        - Linux
        - Mac
        - Windows
    validations:
      required: true

  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      description: Please select the architecture you are using.
      options:
        - x64
        - ARM
        - others (Please specify in the description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        A link to a reproduction repo or steps to reproduce the behaviour.
        Please provide a minimal reproduction or steps to reproduce, see this guide https://stackoverflow.com/help/minimal-reproducible-example
        Why reproduction is required? see this article https://antfu.me/posts/why-reproductions-are-required

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: textarea
    id: info
    attributes:
      label: Full log
      render: text
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context (Optional)
      description: Add any other context about the problem here.
